{
  config,
  lib,
  pkgs,
  inputs,
  ...
}:

{
  # Omarchy (Arch) host — Home Manager runs standalone here, like Pop!_OS.
  #
  # Deliberately NOT imported:
  #   ../common-linux.nix — pulls in alacritty/vscode/windsurf as nix packages.
  #     Omarchy already ships alacritty/chromium via pacman, and nix-built GUI
  #     apps on a non-NixOS distro have OpenGL/driver issues (would need nixGL).
  #   ../services.nix — dconf/GNOME + virt-manager settings; Omarchy is Hyprland.
  imports = [
    ../common.nix
  ];

  home.username = "mir";
  home.homeDirectory = "/home/mir";
  home.stateVersion = "23.05"; # Please read the comment before changing.

  # Omarchy's theme system owns ~/.config/btop — if HM also writes
  # btop.conf, activation refuses to clobber it and Omarchy theme
  # switching would break against a store symlink. Let Omarchy keep it.
  programs.btop.enable = lib.mkForce false;

  # starship.toml IS Home-Manager-owned here, unlike btop: common.nix mirrors
  # Omarchy's shipped starship.toml and uses named colours, so Omarchy themes
  # (which repaint the terminal palette and never edit starship.toml) still
  # apply. First switch on a machine that has Omarchy's copy in place:
  #   mv ~/.config/starship.toml ~/.config/starship.toml.omarchy
  # Note `omarchy-refresh-config starship.toml` would overwrite the HM symlink
  # with a plain file; the next `nh home switch` then needs `-b backup`.
  #
  # Keep common.nix in step with upstream: the fish greeting flags when the
  # shipped file changes from the version common.nix was copied from.
  programs.fish.functions.fish_greeting = ''
    set -l shipped /usr/share/omarchy/config/starship.toml
    if test -r $shipped
      and test (sha256sum $shipped | string split ' ')[1] != b17c9b5f096fc125e97050e359171c6011d6b3c7d7e9ac28f630e75b4d4bb9db
      set_color yellow
      echo "Omarchy updated $shipped — re-sync programs.starship.settings in common.nix (then bump the hash in home-omarchy.nix)"
      set_color normal
    end
  '';

  # Over SSH, common.nix's starship right_format shows user@host in fish, but
  # bash has no right prompt at all, so print user@host right-aligned on the
  # line above the prompt — the blank line starship's add_newline leaves.
  # Sourced by ~/.config/hm/bashrc.sh (see aliases.nix) when SSH_CONNECTION is
  # set.
  xdg.configFile."hm/ssh-prompt.sh".text = ''
    # Generated by Home Manager from home-manager/hosts/home-omarchy.nix.
    # Over SSH, show user@host right-aligned above the bash prompt.
    if [ -n "$SSH_CONNECTION" ]; then
      __hm_ssh_prompt() {
        local user=''${USER:-$(id -un)} host=''${HOSTNAME%%.*}
        local cols=''${COLUMNS:-$(tput cols 2>/dev/null || echo 80)}
        printf '%*s\e[1;33m%s\e[1;32m@%s\e[0m\r' \
          $((cols - ''${#user} - ''${#host} - 1)) "" "$user" "$host"
      }
      # Appended (not prepended): starship_precmd must stay first so it still
      # sees the real $? of the last command.
      PROMPT_COMMAND="''${PROMPT_COMMAND:+$PROMPT_COMMAND;}__hm_ssh_prompt"
    fi
  '';

  # Ghostty config comes from ../ghostty.nix, but as with alacritty the
  # nix-built GUI app would need nixGL here — `sudo pacman -S ghostty`
  # instead; HM only writes ~/.config/ghostty/config.
  programs.ghostty.package = null;
  programs.ghostty.systemd.enable = false;

  home.packages = with pkgs; [
    # CLI-only tools are safe on a foreign distro
    nvd
    killall
    ethtool

    # lang utils
    nixd
    nil
  ];
}
