{
  config,
  lib,
  pkgs,
  inputs,
  ...
}:

{
  # Omarchy (Arch) host — Home Manager runs standalone here, like Pop!_OS.
  #
  # Deliberately NOT imported:
  #   ../common-linux.nix — pulls in alacritty/vscode/windsurf as nix packages.
  #     Omarchy already ships alacritty/chromium via pacman, and nix-built GUI
  #     apps on a non-NixOS distro have OpenGL/driver issues (would need nixGL).
  #   ../services.nix — dconf/GNOME + virt-manager settings; Omarchy is Hyprland.
  imports = [
    ../common.nix
  ];

  home.username = "mir";
  home.homeDirectory = "/home/mir";
  home.stateVersion = "23.05"; # Please read the comment before changing.

  # Omarchy's theme system owns ~/.config/btop — if HM also writes
  # btop.conf, activation refuses to clobber it and Omarchy theme
  # switching would break against a store symlink. Let Omarchy keep it.
  programs.btop.enable = lib.mkForce false;

  # Same story for ~/.config/starship.toml — Omarchy ships and themes it.
  # Empty settings means HM generates no starship.toml, so Omarchy's file
  # stays in place; starship itself remains enabled (fish integration works
  # and picks up Omarchy's config). Drop this override + move the file
  # aside if you'd rather use the HM starship settings from common.nix.
  programs.starship.settings = lib.mkForce { };

  # Because of that, common.nix's starship `right_format` (user@host over
  # SSH) never reaches this host — Omarchy's starship.toml has no hostname
  # module. Do it at the shell level instead, only when SSH_CONNECTION is set:
  #   * fish: a fish_right_prompt (defined after `starship init fish`, so it
  #     replaces starship's empty one). Same colours as common.nix.
  #   * bash: no right prompt exists in bash, so print user@host right-aligned
  #     on the line above the prompt — the blank line starship's add_newline
  #     leaves. Sourced by ~/.config/hm/bashrc.sh (see aliases.nix).
  programs.fish.shellInitLast = ''
    if set -q SSH_CONNECTION; and test "$TERM" != dumb
      function fish_right_prompt
        set_color -o yellow; echo -n $USER
        set_color -o green; echo -n "@"(prompt_hostname)
        set_color normal
      end
    end
  '';

  xdg.configFile."hm/ssh-prompt.sh".text = ''
    # Generated by Home Manager from home-manager/hosts/home-omarchy.nix.
    # Over SSH, show user@host right-aligned above the bash prompt.
    if [ -n "$SSH_CONNECTION" ]; then
      __hm_ssh_prompt() {
        local user=''${USER:-$(id -un)} host=''${HOSTNAME%%.*}
        local cols=''${COLUMNS:-$(tput cols 2>/dev/null || echo 80)}
        printf '%*s\e[1;33m%s\e[1;32m@%s\e[0m\r' \
          $((cols - ''${#user} - ''${#host} - 1)) "" "$user" "$host"
      }
      # Appended (not prepended): starship_precmd must stay first so it still
      # sees the real $? of the last command.
      PROMPT_COMMAND="''${PROMPT_COMMAND:+$PROMPT_COMMAND;}__hm_ssh_prompt"
    fi
  '';

  # Ghostty config comes from ../ghostty.nix, but as with alacritty the
  # nix-built GUI app would need nixGL here — `sudo pacman -S ghostty`
  # instead; HM only writes ~/.config/ghostty/config.
  programs.ghostty.package = null;
  programs.ghostty.systemd.enable = false;

  home.packages = with pkgs; [
    # CLI-only tools are safe on a foreign distro
    nvd
    killall
    ethtool

    # lang utils
    nixd
    nil
  ];
}
