{ config, lib, ... }:

# Shared shell shortcuts — THE place to add/edit aliases.
#
# One definition feeds every shell:
#   * fish (all hosts): via HM's `home.shellAliases` and `programs.fish.shellAbbrs`.
#   * bash on foreign distros HM doesn't manage (Omarchy): via the generated
#     ~/.config/hm/aliases.sh, pulled in by ~/.config/hm/bashrc.sh, which
#     ~/.bashrc sources with a single line:  . "$HOME/.config/hm/bashrc.sh"
#     That file is sourced *after* Omarchy's own aliases, so ours win on
#     name clashes (e.g. `c`).

let
  # Plain aliases — identical in every shell.
  aliases = {
    ll = "ls -al";
    rm = "safe-rm";
    "..." = "cd ../..";
  };

  # Fish abbreviations (expand inline before running). In bash/zsh these are
  # ordinary aliases — same effect, no inline expansion.
  abbrs = {
    gs = "git status";
    ga = "git add .";
    gc = "git commit -m";
    gpull = "git pull origin main";
    gpush = "git push origin main";
    nhos = "nh os switch";
    nhh = "nh home switch";
    c = "clear";
    ff = "fastfetch";
  };

  all = aliases // abbrs;
  posixAliases = lib.concatMapStringsSep "\n"
    (n: "alias ${n}=${lib.escapeShellArg all.${n}}")
    (lib.attrNames all);
in
{
  home.shellAliases = aliases; # HM fans this out to fish (+ bash/zsh if ever enabled)
  programs.fish.shellAbbrs = abbrs;

  # Bridge for shells HM does not manage (Omarchy's bash). Written on every
  # host; harmless where unused.
  xdg.configFile."hm/aliases.sh".text = ''
    # Generated by Home Manager from home-manager/aliases.nix — edit there.
    ${posixAliases}
  '';

  xdg.configFile."hm/bashrc.sh".text = ''
    # Single Home Manager entry point for a bash that HM does not manage
    # (Omarchy). ~/.bashrc needs exactly one line, at the bottom:
    #   . "$HOME/.config/hm/bashrc.sh"
    # Session vars first (PATH, NH_FLAKE, NIX_HOME), then the shared aliases.
    . "$HOME/.nix-profile/etc/profile.d/hm-session-vars.sh"
    . "${config.xdg.configHome}/hm/aliases.sh"
  '';
}
